### ISSUE TITLE
Query about the repository.

### ISSUE THREAD

**Issue by chirag127** [imkrishna-23/python-project#1]
So, is this repository related to the domain training in the college?

**Comment by imkrishna-23** [comment]
No, not all

**Comment by chirag127** [comment]
Okay, by the way, in which domain training you are.

**Comment by imkrishna-23** [comment]
Java

**Comment by chirag127** [comment]
Ah okay, so you didn't made repository for the assignment of Java but doing python

**Comment by imkrishna-23** [comment]
https://github.com/imkrishna-23/BAIC-JAVA.git
now happy

**Comment by chirag127** [comment]
Happy
